#!/usr/bin/env bash

# this file is used by mybinder.org to provide the interactive Jupyter notbooks

set -ex

pip install --upgrade 'pandas>=1.3<1.4'
pip install open-bus-stride-client==$(cat VERSION.txt)
